FunctionBody: fix compiler error when doing implicit cast
Clang is not happy about implicit casts to void*:

FunctionBody.h:1482:33: error: assigning to 'void *' from incompatible type 'Js::JavascriptMethod' (aka 'void *(*)(Js::RecyclableObject *, Js::CallInfo, ...)')
            entryPoint->address = address;
                                ^ ~~~~~~~

We only want the address of the function here so this is safe, add a
C-style cast.