Changes For: ========= CVE-2021-42279: Chakra Scripting Engine Memory Corruption Vulnerability
CVE-2021-42279 is a high-severity memory corruption vulnerability affecting the Chakra Scripting Engine and ChakraCore.

The vulnerability stems from an out-of-bounds write, which can potentially be exploited to achieve remote code execution (RCE). An attacker could exploit this by convincing a user to perform certain actions, leading to memory corruption and potentially allowing the attacker to execute arbitrary code on the affected system.

Vulnerability Type:
=============
Memory Violation, resulting in Remote Code Execution (RCE)

Affected Versions:
============
All versions of ChakraCore up to and including 1.11.24.

Severity:
======
CVSS Score: 7.5 (HIGH)

Root Cause:
=========
# An out-of-bounds array write occurs when a program writes data to a memory location outside the bounds of the allocated memory for an array.
# In the context of ChakraCore, an out-of-bounds write can lead to memory corruption. When data is written outside the bounds of an array, it can overwrite adjacent memory regions that may be used for other variables, objects, or control structures. This unintended overwrite can corrupt data, causing unpredictable behavior or program crashes.
# Consider a simplified scenario where ChakraCore mishandles the bounds of an array:

// JavaScript code that might trigger out-of-bounds write
let arr = new Array(1);
arr[100] = 42; // This could lead to out-of-bounds write if not properly handled

# If ChakraCore does not correctly check the bounds before writing to the ‘arr[100]’ position, it could write the value ‘42’ to a memory location outside the allocated space for ‘arr’. This could overwrite important data or control structures, leading to memory corruption.

Fix:
===
# To address this issue, fix is added to allow setting elements only if the index falls within the bounds of the array.
# This fix is added such that, it takes effect only if additional command line switch “--ValidateArrayBounds” is passed to ChakraCore. With this, we ensure that the existing functionalities of ChakraCore continues to work as before.
# Users of ChakraCore can take advantage of the newly added switch “--ValidateArrayBounds", which helps in making sure, any injection of elements to an array is restricted only within the bounds of the array. With this, we ensure that the out-of-bound write issue is not seen, there by preventing write operation to sensitive memory locations.
# By default, “--ValidateArrayBounds" will be false.

Unit Testing:
==========
All unit test cases are executed and there is no failure due to these new changes. In fact, this fix takes effect only when the switch “--ValidateArrayBounds" is passed to the ChakraCore engine, so there is no impact to existing testcases/functionalities.

Sample Output:
===========
Consider Script "test.js" below:

let arr = new Array(2);
console.log("arr.length is " + arr.length)
arr[0] = 0;
console.log("arr[0] is " + arr[0])
arr[1] = 1;
console.log("arr[1] is " + arr[1])
arr[100] = 100;
console.log("arr[100] is " + arr[100])

Output without the newly added switch,
C:\temp>ch.exe test.js
arr.length is 2
arr[0] is 0
arr[1] is 1
arr[100] is 100

Output with the newly added switch,
C:\temp>ch.exe --ValidateArrayBounds test.js
arr.length is 2
arr[0] is 0
arr[1] is 1
RangeError: Memory index is out of range
   at Global code (C:\temp\test.js:11:1)

References:
========
https://nvd.nist.gov/vuln/detail/CVE-2021-42279
https://www.cve.org/CVERecord?id=CVE-2021-42279
https://github.com/chakra-core/ChakraCore